import unittest
from unittest.mock import Mock
import json
import os

from aegis_trade.agents.macro_analyst import MacroAnalyst
from aegis_trade.agents.runner import AgentRunner
from aegis_trade.domain.reports import ResearchReport

class TestMacroAnalyst(unittest.TestCase):
    def setUp(self):
        self.mock_provider = Mock()
        self.runner = AgentRunner(provider=self.mock_provider)
        
        # Ensure we have a dummy prompt for tests if running from different cwd
        base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        self.prompt_path = os.path.join(base_dir, "prompts", "macro_v1.md")
        # For tests, we assume the prompt file is already generated by the plan

        self.agent = MacroAnalyst(prompt_path=self.prompt_path)

    def test_macro_analyst_bullish(self):
        # Mock LLM response
        fake_response = {
            "macro_bias": "bullish",
            "confidence": 0.85,
            "reasoning": "DXY is weak and yields are falling."
        }
        self.mock_provider.generate.return_value = json.dumps(fake_response)

        context = {
            "dxy_trend": "Bearish",
            "us10y_trend": "Falling"
        }

        result = self.runner.execute(self.agent, context)
        
        self.assertTrue(result.metadata.success)
        self.assertEqual(result.report.capability, "macro_analysis")
        self.assertEqual(result.report.data["macro_bias"], "bullish")
        self.assertEqual(result.report.data["confidence"], 0.85)

if __name__ == '__main__':
    unittest.main()
