from dataclasses import dataclass

@dataclass(frozen=True)
class Version:
    """
    Semantic Version (évolution).
    e.g., "1.2.0"
    """
    value: str

    def __post_init__(self):
        if not self.value:
            raise ValueError("Version cannot be empty.")

@dataclass(frozen=True)
class Alias:
    """
    Human-readable pointer (nom humain).
    e.g., "production", "latest", "staging".
    Mutable pointer to a specific Hash or Version.
    """
    value: str

    def __post_init__(self):
        if not self.value:
            raise ValueError("Alias cannot be empty.")

@dataclass(frozen=True)
class Identity:
    """
    Exact Immutable Identity (Hash).
    Generated by the core.hash.compute_hash function.
    """
    hash_value: str

    def __post_init__(self):
        if not self.hash_value:
            raise ValueError("Hash cannot be empty.")

# Aliases for backward compatibility
VersionSchema = Version

def resolve_version(version_str: str) -> VersionSchema:
    return VersionSchema(version_str)
