from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from typing import Optional

from aegis_trade.domain.core import Symbol

@dataclass(frozen=True)
class OrderIntent:
    """
    An intent to trade, generated by the portfolio/strategy.
    """
    symbol: Symbol
    direction: int         # 1 for Long, -1 for Short
    quantity: float        # Quantity of asset to trade
    target_price: float    # Desired execution price based on current market data
    timestamp: datetime

@dataclass(frozen=True)
class FillEvent:
    """
    A confirmation of execution from the broker.
    """
    symbol: Symbol
    direction: int         # 1 for Long, -1 for Short
    quantity: float        # Actually filled quantity
    fill_price: float      # Final price after slippage
    commission: float      # Costs incurred
    timestamp: datetime    # Time of execution

class IBroker(ABC):
    """
    Port for order execution (simulated or live).
    """
    @abstractmethod
    def execute_order(self, order: OrderIntent) -> Optional[FillEvent]:
        """
        Takes an order intent, applies slippage, commissions and market logic,
        and returns a FillEvent if successfully executed.
        """
        pass
