from typing import List, Tuple, Optional
from datetime import datetime
from dataclasses import dataclass, field
from abc import ABC, abstractmethod

@dataclass
class KronosForecast:
    """
    Represents a time-series forecast generated by the Kronos-mini model.
    """
    symbol: str
    horizon: int
    predicted_values: List[float]
    confidence_interval: Tuple[float, float]
    model_version: str
    timestamp: datetime = field(default_factory=datetime.utcnow)

class IForecaster(ABC):
    """
    Interface for any time-series predictive model (e.g., Kronos).
    Designed to decouple the AI model specifics from the consumers (Agents).
    """
    @abstractmethod
    def get_latest_forecast(self, symbol: str) -> Optional[KronosForecast]:
        """
        Returns the latest available forecast for a given symbol.
        Must be O(1) non-blocking (e.g., read from cache), never synchronous inference.
        """
        pass
