"""
Domain objects for Reasoning Engine (AI-03).
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Dict, Any, Optional, Protocol
from enum import Enum
import uuid

class KnowledgeType(Enum):
    AVOID_PATTERN = "avoid_pattern"
    PREFERRED_PATTERN = "preferred_pattern"
    RISK_OBSERVATION = "risk_observation"
    MARKET_OBSERVATION = "market_observation"


@dataclass
class KnowledgeScore:
    """
    Evaluates the mathematical reliability of a piece of knowledge.
    """
    confidence: float  # Probability of success/failure (0.0 to 1.0)
    support: int       # Number of experiences backing this knowledge
    frequency: float   # Occurrences per week/month
    stability: float   # Does it hold across different market regimes? (0.0 to 1.0)
    recency: float     # How recent are the supporting experiences? (0.0 to 1.0)

    @property
    def total_score(self) -> float:
        """Weighted score to determine if knowledge is still valid."""
        return (self.confidence * 0.4) + (self.stability * 0.3) + (self.recency * 0.3)


@dataclass(kw_only=True)
class Knowledge:
    """
    Base entity for a generated rule or observation.
    """
    type: KnowledgeType
    description: str  # Generated by LLM
    features_conditions: Dict[str, Dict[str, float]]  # e.g., {"rsi": {"min": 70, "max": 100}}
    score: KnowledgeScore
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    active: bool = True
    supporting_experience_ids: List[str] = field(default_factory=list)


@dataclass(kw_only=True)
class AvoidPattern(Knowledge):
    """
    A strict rule signaling a cluster of failures.
    """
    type: KnowledgeType = KnowledgeType.AVOID_PATTERN
    expected_loss_avg: float = 0.0


@dataclass(kw_only=True)
class PreferredPattern(Knowledge):
    """
    A validated configuration with positive edge.
    """
    type: KnowledgeType = KnowledgeType.PREFERRED_PATTERN
    expected_win_avg: float = 0.0


@dataclass(kw_only=True)
class RiskObservation(Knowledge):
    """
    A macro or liquidity observation (e.g., 'Slippage is extremely high on Mondays at 02:00').
    """
    type: KnowledgeType = KnowledgeType.RISK_OBSERVATION


@dataclass(kw_only=True)
class MarketObservation(Knowledge):
    """
    A general observation about market regimes (e.g., 'Trend following is currently underperforming').
    """
    type: KnowledgeType = KnowledgeType.MARKET_OBSERVATION


@dataclass
class KnowledgeVersion:
    """
    Tracks the version of the knowledge base.
    """
    version_id: str
    timestamp: datetime
    active_knowledge_count: int
    archived_knowledge_count: int


@dataclass
class ClusterData:
    """
    Data Transfer Object representing an identified cluster in FAISS.
    """
    cluster_id: int
    size: int
    experience_ids: List[str]
    centroid_features: Dict[str, float]
    variance_features: Dict[str, float]
    is_success_cluster: bool


# --- Interfaces (Ports) ---

class IClusterEngine(Protocol):
    """
    Interface for clustering algorithms (DBSCAN, HDBSCAN, OPTICS).
    """
    def find_clusters(self, vectors: List[List[float]], metadata: List[Dict[str, Any]], epsilon: float = 0.5, min_samples: int = 5) -> List[ClusterData]:
        ...

class ILLMReasoner(Protocol):
    """
    Interface for local LLM text generation based on mathematical context.
    """
    def generate_hypothesis(self, cluster: ClusterData) -> str:
        ...

class IKnowledgeRepository(Protocol):
    """
    Interface for persisting and retrieving Knowledge objects.
    """
    def save(self, knowledge: Knowledge) -> None:
        ...

    def get_all_active(self) -> List[Knowledge]:
        ...

    def get_by_type(self, type: KnowledgeType) -> List[Knowledge]:
        ...
        
    def create_snapshot(self) -> KnowledgeVersion:
        ...
