from dataclasses import dataclass
from datetime import datetime
from aegis_trade.domain.core import Symbol

@dataclass(frozen=True)
class Signal:
    """
    Represents an immutable trading signal generated by a Strategy.
    """
    symbol: Symbol
    direction: int      # 1 for Long, -1 for Short, 0 for neutral
    strength: float     # 0.0 to 1.0 confidence/conviction score
    timestamp: datetime
